### ISSUE TITLE
field validation fails

### ISSUE THREAD

**Issue by dws122** [maithemewp/mai-table-of-contents#10]
when editing a page
https://bizbudding.com/wp-admin/post.php?post=49004&action=edit

this error occurs
<img width="831" alt="Screenshot 2024-08-01 at 12 44 34 AM" src="https://github.com/user-attachments/assets/38403b7e-198c-40e7-98a6-f81754be59e7">

if you click on the exclamation point the following error shows and then any changes made to the page are unable to be saved -- as the save button does not work.

<img width="334" alt="Screenshot 2024-08-01 at 12 43 11 AM" src="https://github.com/user-attachments/assets/98277f18-fa9e-4e57-9986-ca9138aa1fdf">

**Comment by JiveDig** [comment]
Thanks for the report. This will only happen with Mai Engine 2.35.0, which includes ACF 6.3.x with added block validation. I didn't officially release Mai Engine update yet because I think we may hit a few of these issues around. I have an update ready for Mai Notices, and I'll have to get this fixed so they can all get released together.
